= OpenNMS Horizon Demo System

This application stack is a out of the box running demo system of OpenNMS Horizon and different other components.
For more details see https://github.com/opennms-forge/demo.opennms.org/blob/master/docs/README.adoc[here].

== Software Requirements

* JQ
* git
* Docker
* Docker Compose

== Installation

In the current state this applications stack is tested with CentOS only.
Clone this repository and initialize the configuration modules.

[source, bash]
----
git clone https://github.com/opennms-forge/demo.opennms.org.git
cd demo.opennms.org
----

=== Environment variables

In the repositories root folder you will need some environment files.
Especially for setting the passwords in the system.

`.opennms.env`
```
TZ=Europe/Berlin
OPENNMS_DBNAME=opennms
OPENNMS_DBUSER=opennms
OPENNMS_DBPASS=opennms
OPENNMS_GRAFANA=grafana
```

`.grafana.env`
```
GF_SECURITY_ADMIN_PASSWORD=grafana-admin
```

`.postgres.env`
```
TZ=Europe/Berlin
POSTGRES_HOST=database
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
```

=== Elasticsearch cluster

The `vm.max_map_count` kernel setting needs to be set to at least 262144 for production use.

```
$ grep vm.max_map_count /etc/sysctl.conf
vm.max_map_count=262144
```

To apply the setting on a live system type: `sysctl -w vm.max_map_count=262144`

The deploy script will do it automatically!

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode


=== Initiate the application stack

The process contains a full redeploy, so the current system (if it is running) will deleted completely.
**All rrd archives and Postgresql database will be lost!**

Run as `root`:
[source, bash]
----
cd setup
./init.sh
----

=== Daily restart

The init file is creating a cron entry in `/etc/crontab` to restart the Docker deamon once a day.
So be careful when deploying this setup on machines with other Docker containers running!

== Accessing the components

OpenNMS: http://localhost:8980/opennms

Grafana: http://localhost:3000

== Usage 

=== OpenNMS user accounts and passwords

These user accounts work out of the box and are defined in `users.xml`.

* Administrator: `admin:admin`
* Demo User: `demo:demo`
* Grafana User: `grafana:grafana`
* Minion User: `minion:minion`

=== Scripts 

There are some script which are used to setup the application stack. They can be found in the `setup` folder and are described https://github.com/opennms-forge/demo.opennms.org/blob/master/setup/README.adoc[here].

=== Restart application stack

To restart the whole stack use:
[source, bash]
----
docker-compose restart
----
=== Configuration updates

Local configuration changes in `etc-overlay` can be reloaded with:
[source, bash]
----
docker-compose down && docker-compose up -d
----

=== Updating the stack

The Horizon image definition in the docker-compose file is set to a specific version. For example:

```
horizon:
  image: opennms/horizon-core-web:23.0.2-1
```

Just replace this version with an other version and run `docker-compose pull` which will do an upgrade.


== Supporting this project

=== Enhancements & Ideas

Ideas for new implementations of other OpenNMS features can be documented in the issue section.

=== Configuration updates

Configuration updates or changes should be provided as a pull request.
