= OpenNMS Horizon Demo System

This application stack is a out of the box running demo system of OpenNMS Horizon and different other components.
For more details see https://github.com/opennms-forge/demo.opennms.org/blob/master/docs/README.adoc[here].

== Software Requirements

* git
* Docker
* Docker Compose

== Installation

In the current state this applications stack is tested with CentOS only.
Clone this repository and initialize the configuration modules.

[source, bash]
----
git clone https://github.com/opennms-forge/demo.opennms.org.git
cd demo.opennms.org
git submodule update --init
----

=== Environment variables

In the repositories root folder you will need some environment files.
Especially for setting the passwords in the system.

`.opennms.env`
```
TZ=Europe/Berlin
OPENNMS_DBNAME=opennms
OPENNMS_DBUSER=opennms
OPENNMS_DBPASS=PASSWORD
OPENNMS_ADMIN=admin
OPENNMS_ADMIN_SALT=ADMINS_SALT
OPENNMS_GRAFANA=PASSWORD_FOR_GRAFANA_USER
```

`.grafana.env`
```
GF_SECURITY_ADMIN_PASSWORD=PASSWORD_FOR_GRAFANA_ADMIN
```

`.postgres.env`
```
TZ=Europe/Berlin
POSTGRES_HOST=database
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=PASSWORD_FOR_POSTGRES_USER
```

=== Initiate the application stack

The process contains a full redeploy, so the current system (if it is running) will deleted completely.
**All rrd archives and Postgresql database will be lost!**

[source, bash]
----
cd setup
./init.sh
----

== Accessing the components

OpenNMS: http://localhost:8980/opennms

Grafana: http://localhost:3000

== Usage 

There are some script which are used to setup the application stack. They can be found in the `setup` folder and are described https://github.com/opennms-forge/demo.opennms.org/blob/master/setup/README.adoc[here].

=== Restart application stack

To restart the whole stack use:
[source, bash]
----
docker-compose restart
----
=== Configuration updates

Local configuration changes in `etc-overlay` can be reloaded with:
[source, bash]
----
docker-compose up -d
----

=== Updating the stack

Docker-compose file already use `latest` repo, so a re-deploy explained above or `docker-compose pull` will do an upgrade.


== Supporting this project

=== Enhancements & Ideas

Ideas for new implementations of other OpenNMS features can be documented in the issue section.

=== Configuration updates

Configuration updates or changes should be provided as a pull request.
